/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErpOracleRouteImport } from './routes/erp-oracle'
import { Route as ErpSapRouteImport } from './routes/erp-sap'
import { Route as FlarCyberRouteImport } from './routes/flar-cyber'
import { Route as GovernancaEFiscalRouteImport } from './routes/governanca-e-fiscal'
import { Route as HiperautomacaoRouteImport } from './routes/hiperautomacao'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as SalesforceRouteImport } from './routes/salesforce'
import { Route as TalentosEDesenvolvimentoRouteImport } from './routes/talentos-e-desenvolvimento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpOracleRoute = ErpOracleRouteImport.update({
  id: '/erp-oracle',
  path: '/erp-oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpSapRoute = ErpSapRouteImport.update({
  id: '/erp-sap',
  path: '/erp-sap',
  getParentRoute: () => rootRouteImport,
} as any)
const FlarCyberRoute = FlarCyberRouteImport.update({
  id: '/flar-cyber',
  path: '/flar-cyber',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancaEFiscalRoute = GovernancaEFiscalRouteImport.update({
  id: '/governanca-e-fiscal',
  path: '/governanca-e-fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const HiperautomacaoRoute = HiperautomacaoRouteImport.update({
  id: '/hiperautomacao',
  path: '/hiperautomacao',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesforceRoute = SalesforceRouteImport.update({
  id: '/salesforce',
  path: '/salesforce',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentosEDesenvolvimentoRoute =
  TalentosEDesenvolvimentoRouteImport.update({
    id: '/talentos-e-desenvolvimento',
    path: '/talentos-e-desenvolvimento',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/erp-oracle': typeof ErpOracleRoute
  '/erp-sap': typeof ErpSapRoute
  '/flar-cyber': typeof FlarCyberRoute
  '/governanca-e-fiscal': typeof GovernancaEFiscalRoute
  '/hiperautomacao': typeof HiperautomacaoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/salesforce': typeof SalesforceRoute
  '/talentos-e-desenvolvimento': typeof TalentosEDesenvolvimentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/erp-oracle': typeof ErpOracleRoute
  '/erp-sap': typeof ErpSapRoute
  '/flar-cyber': typeof FlarCyberRoute
  '/governanca-e-fiscal': typeof GovernancaEFiscalRoute
  '/hiperautomacao': typeof HiperautomacaoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/salesforce': typeof SalesforceRoute
  '/talentos-e-desenvolvimento': typeof TalentosEDesenvolvimentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/erp-oracle': typeof ErpOracleRoute
  '/erp-sap': typeof ErpSapRoute
  '/flar-cyber': typeof FlarCyberRoute
  '/governanca-e-fiscal': typeof GovernancaEFiscalRoute
  '/hiperautomacao': typeof HiperautomacaoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/salesforce': typeof SalesforceRoute
  '/talentos-e-desenvolvimento': typeof TalentosEDesenvolvimentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/erp-oracle'
    | '/erp-sap'
    | '/flar-cyber'
    | '/governanca-e-fiscal'
    | '/hiperautomacao'
    | '/quem-somos'
    | '/salesforce'
    | '/talentos-e-desenvolvimento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/erp-oracle'
    | '/erp-sap'
    | '/flar-cyber'
    | '/governanca-e-fiscal'
    | '/hiperautomacao'
    | '/quem-somos'
    | '/salesforce'
    | '/talentos-e-desenvolvimento'
  id:
    | '__root__'
    | '/'
    | '/erp-oracle'
    | '/erp-sap'
    | '/flar-cyber'
    | '/governanca-e-fiscal'
    | '/hiperautomacao'
    | '/quem-somos'
    | '/salesforce'
    | '/talentos-e-desenvolvimento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErpOracleRoute: typeof ErpOracleRoute
  ErpSapRoute: typeof ErpSapRoute
  FlarCyberRoute: typeof FlarCyberRoute
  GovernancaEFiscalRoute: typeof GovernancaEFiscalRoute
  HiperautomacaoRoute: typeof HiperautomacaoRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SalesforceRoute: typeof SalesforceRoute
  TalentosEDesenvolvimentoRoute: typeof TalentosEDesenvolvimentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp-oracle': {
      id: '/erp-oracle'
      path: '/erp-oracle'
      fullPath: '/erp-oracle'
      preLoaderRoute: typeof ErpOracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp-sap': {
      id: '/erp-sap'
      path: '/erp-sap'
      fullPath: '/erp-sap'
      preLoaderRoute: typeof ErpSapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flar-cyber': {
      id: '/flar-cyber'
      path: '/flar-cyber'
      fullPath: '/flar-cyber'
      preLoaderRoute: typeof FlarCyberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governanca-e-fiscal': {
      id: '/governanca-e-fiscal'
      path: '/governanca-e-fiscal'
      fullPath: '/governanca-e-fiscal'
      preLoaderRoute: typeof GovernancaEFiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiperautomacao': {
      id: '/hiperautomacao'
      path: '/hiperautomacao'
      fullPath: '/hiperautomacao'
      preLoaderRoute: typeof HiperautomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salesforce': {
      id: '/salesforce'
      path: '/salesforce'
      fullPath: '/salesforce'
      preLoaderRoute: typeof SalesforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talentos-e-desenvolvimento': {
      id: '/talentos-e-desenvolvimento'
      path: '/talentos-e-desenvolvimento'
      fullPath: '/talentos-e-desenvolvimento'
      preLoaderRoute: typeof TalentosEDesenvolvimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErpOracleRoute: ErpOracleRoute,
  ErpSapRoute: ErpSapRoute,
  FlarCyberRoute: FlarCyberRoute,
  GovernancaEFiscalRoute: GovernancaEFiscalRoute,
  HiperautomacaoRoute: HiperautomacaoRoute,
  QuemSomosRoute: QuemSomosRoute,
  SalesforceRoute: SalesforceRoute,
  TalentosEDesenvolvimentoRoute: TalentosEDesenvolvimentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
